### ISSUE TITLE
URL bar broken?

### ISSUE THREAD

**Issue by jackwilsdon** [Walkman100/BasicBrowser#9]
When typing in the URL bar, the text is cleared and reset back to the current URL. I am using BasicBrowser v1.2.2 Portable.

![](https://cloud.githubusercontent.com/assets/1843197/4780189/d545ec36-5c5c-11e4-8973-a72f0e3045c5.gif)

**Comment by Walkman100** [comment]
Hmm. I didn't notice this, since the page that I have set as my homepage loads almost immediately. Looking at the code, it seems that [this](https://github.com/Walkman100/BasicBrowser/blob/master/BasicBrowser.vb#L319) line is setting it, while [this](https://github.com/Walkman100/BasicBrowser/blob/master/BasicBrowser.vb#L346) line is waiting for focus to be lost.

**Comment by Walkman100** [comment]
Fixed with release [v1.2.2.1](https://github.com/Walkman100/BasicBrowser/releases/tag/v1.2.2.1). Sorry about that.
